### ISSUE TITLE
src/icons/entypo/cc.tvg

### ISSUE THREAD

**Issue by JosephABudd** [david-vanderson/dvui#168] opened 2024-12-03 13:50 UTC
In the demo and in the source files, is **cc**.tvg supposed to be **cw** for "clock wise".

**Comment by david-vanderson** [comment] 2024-12-04 00:38
Yep - you are right.  Somehow we had a cc.tvg that was a duplicate of cw.tvg.  I must have messed that up back when converting the entypo icons to tvg.  Should be fixed now.  Thanks!

**Closed by david-vanderson** 2024-12-04 00:38 UTC
